language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: ok8m5Bnl3ZlNtTWxq4c+T+n9BAG0BGAPELPy/i0A7iTnQn0JTrtJxQ3oyZ1xtf64scbBlrQhmBc0APqvqaTfAoC0TV9pG0Jvmw0PZlVQU9Ip9d1YbZ7suI0p/Pj0/Cu000B+pNvu2qAaNUx96o9aApATl18xPgatom6HiB7HsqHCNjGFgFXdpjlEKwjY9ni7aYoelp+squfJxbYBO30KiRfGGLiLaVfdGSRtZovYkPu6Nj74tPqWSMIpWy1DSmEcteKLLWuEwU6WnYKqL/5itiGxEry8QG3ScifGG9yaWAFPsMVd4aG1HYwwK7bqTOmEjqGE0XC3YO2fUdJxsReu8xyK6ZYqHsxUNTkliekcAgTlYnpGZsPzRrbW631pH7/ETbXRfOrzbHgF73S5fzwArITmFilwgq/sL7kD0XJ19Ys7fky6nEicY6kXH4QZ8M4v4Hi+3Sf8QdlKfcI0oAIygNJVwawBptM9DJVrU5NCJFrDLwM0fRWU29y4MJjUR6slS1RvGxzI2xclSF4zuQ3bgt01Y+rDu8Tf3neZTm2dA7yjZX0alkvRcVYOaZK1JzwAGKN3iMxVz8FPdySs9DzoT/yFTXdYIrr28D/4jvRBMEIHI/UyYGgMbNwXMQZm7hJ72SWGSxD0lkBFLuZtzZMVql2ZkROGd4tuUByTrGVyCBc=
  app: wc2018-bot
