language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: sc/EvRxDwjvBJ+1PgJJGe6o5F+/s6VOVLjKFRqIy0umfPh8DrBVn1OqTiI7AZSfQX9VT0g7gj03HVFE38ZpVIwlgPsn2pHLQoVOFgNxr0VOObfS/3GHCPh1664t682VJlLavCVD4dxzbxUspypplK5p4e16jAfSDPc0v/Ubnd234WPZQM8TrrqmnL3C4U7Bz4/8Ai7VRpEbONn1tmZVE6qXSh2PsidhEa2KutQEC0ATyf5DKXTyC7DpiZdik0h8o3rc0kk4XHRJ/Ji9rtu4rI8atq0/4ZWDhBeMrGXdYs504uzefeiTvcocZHlX93gI3uRillyAOVwS483QK/OTtVVRjfw22xXkORJiJohBh1T/CMh0pWiRbcfjcYGxxYnHWB/zL7uEtwCzuFQ7jeCM2vAKOwUhzRPZuCWX02Blc6jmxxtuGuwNeYRxEz7UPvSLXASBpGlvJmesehJaOUUaxVbs607Rlgn58RwS/McbfwzGt32OfMuqEBTheZO4Q9WsSCMpJFJJTdzWmUIFRUKPJqjfxUrFHqYorQwZJOGRwRM8911rTlrDyPsQauTaUeeUeB/2YM7iNvglBBTCC0U3llLGPXpNjYW7Hy2cHIo/xy/OcizRskNsjyOCqgrw/hXNtNw3R/2qNQwywh5uWD+Kw+1O4T9d6eFX1qgsWa/bSEGQ=
  app: wc2018-bot
