language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: eXT7u6SvsyXnf6kWqBV7uKv4ERZqXDbiZpcclUdnY5hAgcZ+VnrwV8XSJIzQGJC0htldkz4/mVmCMy9XrJ0/Xa4AMoPFK61oh6yKEiSSEHFibGVwfJZFqEFI+uKLHJa0PskVyqzRwDaql0TRa/dEh4fdHwehiJngves2CQo/IiPgT+Pj1ZwjwP8tD6v3pvExXq0DQvgXcD7D9/NivilAihQumQ7AjAgmph6jd57K0hcaMqcYyCGoPXQ02WV4tcGz5nqfCUiNqdJRrKnYcd6TLe6/X6dLDRJL4DrYL3tiGNL5S5+7TX4xszFSCuryQ4S6nbyyvvcMSpHhICGSlDILxdpN05sIpP82ck5UOR47NhFNkw1b4AmZeFwMQKvAfZaEEtIpdlVwF0q2GvzYvWVm0rX3bngEf5zd4shHb7xYIflUzxkHnY/IxVuRHeky8XTUnjNM4IcUiofGjuHuQrvpbOZlYg5hvMrhO+i2XOFCpfgO5NsDetsnn5s1NSWRyE311/OAP1/iLHWmBA8WU3lg13h/tFFtaAOwYvLglj8iwzyzQaleCiwd96sXaXguLzAFfvoymjXus1rDpA/QJk8V1yAH1BRovBMaI6XBmTS37CuMbwaadfLmBpvmrOeBuJDunNmNMO/fKDB5meaxFhqphweIxLHXN+E83HiExgwTQYE=
  app: wc2018-bot
